<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251219154951 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE actualites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, type_source VARCHAR(50) NOT NULL, url_source VARCHAR(500) DEFAULT NULL, date_publication TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ville_id INT NOT NULL, auteur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75315B6DA73F0036 ON actualites (ville_id)');
        $this->addSql('CREATE INDEX IDX_75315B6D60BB6FE6 ON actualites (auteur_id)');
        $this->addSql('CREATE TABLE categories_citoyens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_121EF707A73F0036 ON categories_citoyens (ville_id)');
        $this->addSql('CREATE TABLE commentaires_signalement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, modifie BOOLEAN DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signalement_id INT NOT NULL, auteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7098601D65C5E57E ON commentaires_signalement (signalement_id)');
        $this->addSql('CREATE INDEX IDX_7098601D60BB6FE6 ON commentaires_signalement (auteur_id)');
        $this->addSql('CREATE TABLE evenements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(500) DEFAULT NULL, thematique_id INT NOT NULL, ville_id INT NOT NULL, cree_par INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E10AD400476556AF ON evenements (thematique_id)');
        $this->addSql('CREATE INDEX IDX_E10AD400A73F0036 ON evenements (ville_id)');
        $this->addSql('CREATE INDEX IDX_E10AD4004C28E2B5 ON evenements (cree_par)');
        $this->addSql('CREATE TABLE evenements_utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_ajout TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, utilisateur_id INT NOT NULL, evenement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C6484F15FB88E14F ON evenements_utilisateur (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_C6484F15FD02F13 ON evenements_utilisateur (evenement_id)');
        $this->addSql('CREATE TABLE fichiers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_original VARCHAR(255) NOT NULL, nom_stockage VARCHAR(255) NOT NULL, chemin VARCHAR(500) NOT NULL, type_mime VARCHAR(100) NOT NULL, taille_octets BIGINT NOT NULL, hash_sha256 VARCHAR(64) DEFAULT NULL, date_upload TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uploade_par INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_969DB4AB4B23C510 ON fichiers (uploade_par)');
        $this->addSql('CREATE TABLE historique_signalements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ancien_etat VARCHAR(50) DEFAULT NULL, nouvel_etat VARCHAR(50) NOT NULL, commentaire TEXT DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signalement_id INT NOT NULL, modifie_par INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A528C44465C5E57E ON historique_signalements (signalement_id)');
        $this->addSql('CREATE INDEX IDX_A528C4448D3DBC34 ON historique_signalements (modifie_par)');
        $this->addSql('CREATE TABLE logs_actions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, adresse_ip VARCHAR(45) DEFAULT NULL, date_action TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B96AAFAFB88E14F ON logs_actions (utilisateur_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, message TEXT NOT NULL, type VARCHAR(50) NOT NULL, lue BOOLEAN DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_lecture TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, destinataire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A4F84F6E ON notifications (destinataire_id)');
        $this->addSql('CREATE TABLE quartiers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E2F7BE8A73F0036 ON quartiers (ville_id)');
        $this->addSql('CREATE TABLE questions_sondage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, ordre INT DEFAULT NULL, sondage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FCE859BAF4AE56 ON questions_sondage (sondage_id)');
        $this->addSql('CREATE TABLE reponses_sondage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, choix_reponse TEXT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A78D7221E27F6BF ON reponses_sondage (question_id)');
        $this->addSql('CREATE TABLE reseaux_sociaux (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plateforme VARCHAR(50) NOT NULL, url VARCHAR(500) NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79E212C8A73F0036 ON reseaux_sociaux (ville_id)');
        $this->addSql('CREATE TABLE signalements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, latitude NUMERIC(10, 2) DEFAULT NULL, longitude NUMERIC(10, 2) DEFAULT NULL, adresse VARCHAR(500) DEFAULT NULL, type_signalement VARCHAR(50) NOT NULL, etat VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fichier_id INT DEFAULT NULL, citoyen_id INT NOT NULL, quartier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_120AE27F915CFE ON signalements (fichier_id)');
        $this->addSql('CREATE INDEX IDX_120AE2743787BBA ON signalements (citoyen_id)');
        $this->addSql('CREATE INDEX IDX_120AE27DF1E57AB ON signalements (quartier_id)');
        $this->addSql('CREATE TABLE sondages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ville_id INT NOT NULL, quartier_id INT DEFAULT NULL, categorie_id INT DEFAULT NULL, cree_par INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7BCB3816A73F0036 ON sondages (ville_id)');
        $this->addSql('CREATE INDEX IDX_7BCB3816DF1E57AB ON sondages (quartier_id)');
        $this->addSql('CREATE INDEX IDX_7BCB3816BCF5E72D ON sondages (categorie_id)');
        $this->addSql('CREATE INDEX IDX_7BCB38164C28E2B5 ON sondages (cree_par)');
        $this->addSql('CREATE TABLE thematiques_evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E16BAF03A73F0036 ON thematiques_evenement (ville_id)');
        $this->addSql('CREATE TABLE utilisateurs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, mot_de_passe_hash VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, adresse VARCHAR(500) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, date_naissance DATE DEFAULT NULL, consentement_rgpd BOOLEAN NOT NULL, date_consentement_rgpd TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, derniere_connexion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, compte_actif BOOLEAN DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ville_id INT NOT NULL, quartier_id INT DEFAULT NULL, categorie_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_497B315EA73F0036 ON utilisateurs (ville_id)');
        $this->addSql('CREATE INDEX IDX_497B315EDF1E57AB ON utilisateurs (quartier_id)');
        $this->addSql('CREATE INDEX IDX_497B315EBCF5E72D ON utilisateurs (categorie_id)');
        $this->addSql('CREATE TABLE villes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_ville VARCHAR(255) NOT NULL, slogan VARCHAR(500) DEFAULT NULL, logo_url VARCHAR(500) DEFAULT NULL, couleurs_theme VARCHAR(100) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE votes_sondage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_vote TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sondage_id INT NOT NULL, citoyen_id INT NOT NULL, question_id INT NOT NULL, reponse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9BABF17CBAF4AE56 ON votes_sondage (sondage_id)');
        $this->addSql('CREATE INDEX IDX_9BABF17C43787BBA ON votes_sondage (citoyen_id)');
        $this->addSql('CREATE INDEX IDX_9BABF17C1E27F6BF ON votes_sondage (question_id)');
        $this->addSql('CREATE INDEX IDX_9BABF17CCF18BB82 ON votes_sondage (reponse_id)');
        $this->addSql('ALTER TABLE actualites ADD CONSTRAINT FK_75315B6DA73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE actualites ADD CONSTRAINT FK_75315B6D60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories_citoyens ADD CONSTRAINT FK_121EF707A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaires_signalement ADD CONSTRAINT FK_7098601D65C5E57E FOREIGN KEY (signalement_id) REFERENCES signalements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaires_signalement ADD CONSTRAINT FK_7098601D60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenements ADD CONSTRAINT FK_E10AD400476556AF FOREIGN KEY (thematique_id) REFERENCES thematiques_evenement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenements ADD CONSTRAINT FK_E10AD400A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenements ADD CONSTRAINT FK_E10AD4004C28E2B5 FOREIGN KEY (cree_par) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenements_utilisateur ADD CONSTRAINT FK_C6484F15FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenements_utilisateur ADD CONSTRAINT FK_C6484F15FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fichiers ADD CONSTRAINT FK_969DB4AB4B23C510 FOREIGN KEY (uploade_par) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_signalements ADD CONSTRAINT FK_A528C44465C5E57E FOREIGN KEY (signalement_id) REFERENCES signalements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_signalements ADD CONSTRAINT FK_A528C4448D3DBC34 FOREIGN KEY (modifie_par) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE logs_actions ADD CONSTRAINT FK_7B96AAFAFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A4F84F6E FOREIGN KEY (destinataire_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quartiers ADD CONSTRAINT FK_5E2F7BE8A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questions_sondage ADD CONSTRAINT FK_6FCE859BAF4AE56 FOREIGN KEY (sondage_id) REFERENCES sondages (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reponses_sondage ADD CONSTRAINT FK_3A78D7221E27F6BF FOREIGN KEY (question_id) REFERENCES questions_sondage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reseaux_sociaux ADD CONSTRAINT FK_79E212C8A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE27F915CFE FOREIGN KEY (fichier_id) REFERENCES fichiers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE2743787BBA FOREIGN KEY (citoyen_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE27DF1E57AB FOREIGN KEY (quartier_id) REFERENCES quartiers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sondages ADD CONSTRAINT FK_7BCB3816A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sondages ADD CONSTRAINT FK_7BCB3816DF1E57AB FOREIGN KEY (quartier_id) REFERENCES quartiers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sondages ADD CONSTRAINT FK_7BCB3816BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories_citoyens (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sondages ADD CONSTRAINT FK_7BCB38164C28E2B5 FOREIGN KEY (cree_par) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thematiques_evenement ADD CONSTRAINT FK_E16BAF03A73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateurs ADD CONSTRAINT FK_497B315EA73F0036 FOREIGN KEY (ville_id) REFERENCES villes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateurs ADD CONSTRAINT FK_497B315EDF1E57AB FOREIGN KEY (quartier_id) REFERENCES quartiers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateurs ADD CONSTRAINT FK_497B315EBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories_citoyens (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes_sondage ADD CONSTRAINT FK_9BABF17CBAF4AE56 FOREIGN KEY (sondage_id) REFERENCES sondages (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes_sondage ADD CONSTRAINT FK_9BABF17C43787BBA FOREIGN KEY (citoyen_id) REFERENCES utilisateurs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes_sondage ADD CONSTRAINT FK_9BABF17C1E27F6BF FOREIGN KEY (question_id) REFERENCES questions_sondage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes_sondage ADD CONSTRAINT FK_9BABF17CCF18BB82 FOREIGN KEY (reponse_id) REFERENCES reponses_sondage (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE actualites DROP CONSTRAINT FK_75315B6DA73F0036');
        $this->addSql('ALTER TABLE actualites DROP CONSTRAINT FK_75315B6D60BB6FE6');
        $this->addSql('ALTER TABLE categories_citoyens DROP CONSTRAINT FK_121EF707A73F0036');
        $this->addSql('ALTER TABLE commentaires_signalement DROP CONSTRAINT FK_7098601D65C5E57E');
        $this->addSql('ALTER TABLE commentaires_signalement DROP CONSTRAINT FK_7098601D60BB6FE6');
        $this->addSql('ALTER TABLE evenements DROP CONSTRAINT FK_E10AD400476556AF');
        $this->addSql('ALTER TABLE evenements DROP CONSTRAINT FK_E10AD400A73F0036');
        $this->addSql('ALTER TABLE evenements DROP CONSTRAINT FK_E10AD4004C28E2B5');
        $this->addSql('ALTER TABLE evenements_utilisateur DROP CONSTRAINT FK_C6484F15FB88E14F');
        $this->addSql('ALTER TABLE evenements_utilisateur DROP CONSTRAINT FK_C6484F15FD02F13');
        $this->addSql('ALTER TABLE fichiers DROP CONSTRAINT FK_969DB4AB4B23C510');
        $this->addSql('ALTER TABLE historique_signalements DROP CONSTRAINT FK_A528C44465C5E57E');
        $this->addSql('ALTER TABLE historique_signalements DROP CONSTRAINT FK_A528C4448D3DBC34');
        $this->addSql('ALTER TABLE logs_actions DROP CONSTRAINT FK_7B96AAFAFB88E14F');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A4F84F6E');
        $this->addSql('ALTER TABLE quartiers DROP CONSTRAINT FK_5E2F7BE8A73F0036');
        $this->addSql('ALTER TABLE questions_sondage DROP CONSTRAINT FK_6FCE859BAF4AE56');
        $this->addSql('ALTER TABLE reponses_sondage DROP CONSTRAINT FK_3A78D7221E27F6BF');
        $this->addSql('ALTER TABLE reseaux_sociaux DROP CONSTRAINT FK_79E212C8A73F0036');
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE27F915CFE');
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE2743787BBA');
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE27DF1E57AB');
        $this->addSql('ALTER TABLE sondages DROP CONSTRAINT FK_7BCB3816A73F0036');
        $this->addSql('ALTER TABLE sondages DROP CONSTRAINT FK_7BCB3816DF1E57AB');
        $this->addSql('ALTER TABLE sondages DROP CONSTRAINT FK_7BCB3816BCF5E72D');
        $this->addSql('ALTER TABLE sondages DROP CONSTRAINT FK_7BCB38164C28E2B5');
        $this->addSql('ALTER TABLE thematiques_evenement DROP CONSTRAINT FK_E16BAF03A73F0036');
        $this->addSql('ALTER TABLE utilisateurs DROP CONSTRAINT FK_497B315EA73F0036');
        $this->addSql('ALTER TABLE utilisateurs DROP CONSTRAINT FK_497B315EDF1E57AB');
        $this->addSql('ALTER TABLE utilisateurs DROP CONSTRAINT FK_497B315EBCF5E72D');
        $this->addSql('ALTER TABLE votes_sondage DROP CONSTRAINT FK_9BABF17CBAF4AE56');
        $this->addSql('ALTER TABLE votes_sondage DROP CONSTRAINT FK_9BABF17C43787BBA');
        $this->addSql('ALTER TABLE votes_sondage DROP CONSTRAINT FK_9BABF17C1E27F6BF');
        $this->addSql('ALTER TABLE votes_sondage DROP CONSTRAINT FK_9BABF17CCF18BB82');
        $this->addSql('DROP TABLE actualites');
        $this->addSql('DROP TABLE categories_citoyens');
        $this->addSql('DROP TABLE commentaires_signalement');
        $this->addSql('DROP TABLE evenements');
        $this->addSql('DROP TABLE evenements_utilisateur');
        $this->addSql('DROP TABLE fichiers');
        $this->addSql('DROP TABLE historique_signalements');
        $this->addSql('DROP TABLE logs_actions');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE quartiers');
        $this->addSql('DROP TABLE questions_sondage');
        $this->addSql('DROP TABLE reponses_sondage');
        $this->addSql('DROP TABLE reseaux_sociaux');
        $this->addSql('DROP TABLE signalements');
        $this->addSql('DROP TABLE sondages');
        $this->addSql('DROP TABLE thematiques_evenement');
        $this->addSql('DROP TABLE utilisateurs');
        $this->addSql('DROP TABLE villes');
        $this->addSql('DROP TABLE votes_sondage');
    }
}
