
GRANT USAGE ON SCHEMA public TO unicity_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO unicity_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO unicity_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO unicity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO unicity_user;