-- ============================================================================
-- BASE DE DONNÉES AMÉLIORÉE - APPLICATION UNICITY
-- Version : 2.0 (Améliorée selon cahier des charges)
-- Date : 2025-12-06
-- SGBD : PostgreSQL 15+
-- ============================================================================

-- ============================================================================
-- 1. CRÉATION DES TABLES
-- ============================================================================

-- Table : villes
-- Description : Gestion des villes clientes avec personnalisation (logo, slogan, couleurs)
CREATE TABLE "villes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_ville" VARCHAR(255) NOT NULL,
  "slogan" VARCHAR(500),
  "logo_url" VARCHAR(500),
  "couleurs_theme" VARCHAR(100), -- Format JSON ou CSS (ex: {"primary": "#FF5733", "secondary": "#3498db"})
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : quartiers
-- Description : Découpage géographique des villes pour filtrage des sondages et événements
CREATE TABLE "quartiers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(255) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : categories_citoyens
-- Description : Catégorisation des citoyens pour ciblage des sondages (ex: parents d'élèves, seniors, commerçants)
CREATE TABLE "categories_citoyens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" VARCHAR(255) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : utilisateurs
-- Description : Gestion des comptes utilisateurs (citoyens, élus, agents municipaux)
CREATE TABLE "utilisateurs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(100) NOT NULL,
  "prenom" VARCHAR(100) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "mot_de_passe_hash" VARCHAR(255) NOT NULL, -- Stockage hashé (bcrypt/argon2)
  "role" VARCHAR(50) NOT NULL CHECK ("role" IN ('citoyen', 'elu', 'agent_municipal')),
  "adresse" VARCHAR(500),
  "ville_id" INT NOT NULL,
  "quartier_id" INT,
  "categorie_id" INT,
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : signalements
-- Description : Signalements de problèmes par les citoyens (voirie, éclairage, propreté)
CREATE TABLE "signalements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "photo_url" VARCHAR(500),
  "latitude" DECIMAL(10, 8), -- Précision GPS (ex: 48.8566)
  "longitude" DECIMAL(11, 8), -- Précision GPS (ex: 2.3522)
  "type_signalement" VARCHAR(50) NOT NULL CHECK ("type_signalement" IN ('voirie', 'eclairage', 'proprete', 'autre')),
  "etat" VARCHAR(50) NOT NULL DEFAULT 'enregistre' CHECK ("etat" IN ('enregistre', 'en_cours', 'resolu')),
  "citoyen_id" INT NOT NULL,
  "quartier_id" INT, -- Permet de filtrer les signalements par quartier
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "date_modification" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : sondages
-- Description : Sondages et consultations publiques créés par la mairie
CREATE TABLE "sondages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "date_debut" TIMESTAMP NOT NULL,
  "date_fin" TIMESTAMP NOT NULL,
  "quartier_id" INT, -- NULL = tous les quartiers
  "categorie_id" INT, -- NULL = toutes les catégories
  "ville_id" INT NOT NULL,
  "cree_par" INT NOT NULL,
  CONSTRAINT "check_dates_sondage" CHECK ("date_fin" > "date_debut")
);

-- Table : questions_sondage
-- Description : Questions d'un sondage (un sondage peut avoir plusieurs questions)
CREATE TABLE "questions_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sondage_id" INT NOT NULL,
  "question" TEXT NOT NULL,
  "ordre" INT DEFAULT 1 -- Permet d'ordonner les questions
);

-- Table : reponses_sondage
-- Description : Choix de réponses possibles pour une question de sondage
CREATE TABLE "reponses_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" INT NOT NULL,
  "choix_reponse" TEXT NOT NULL
);

-- Table : votes_sondage
-- Description : Votes des citoyens aux sondages
CREATE TABLE "votes_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sondage_id" INT NOT NULL,
  "citoyen_id" INT NOT NULL,
  "reponse_id" INT NOT NULL,
  "date_vote" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("sondage_id", "citoyen_id", "reponse_id") -- Un citoyen ne peut voter qu'une fois par question
);

-- Table : thematiques_evenement
-- Description : Thématiques des événements (sport, culture, citoyenneté, environnement)
CREATE TABLE "thematiques_evenement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(100) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : evenements
-- Description : Événements de la ville et des associations locales
CREATE TABLE "evenements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "date_debut" TIMESTAMP NOT NULL,
  "date_fin" TIMESTAMP NOT NULL,
  "lieu" VARCHAR(500), -- Ajout du lieu de l'événement
  "thematique_id" INT NOT NULL,
  "ville_id" INT NOT NULL,
  "cree_par" INT NOT NULL,
  CONSTRAINT "check_dates_evenement" CHECK ("date_fin" >= "date_debut")
);

-- Table : evenements_utilisateur
-- Description : Événements ajoutés au calendrier personnel des utilisateurs
CREATE TABLE "evenements_utilisateur" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utilisateur_id" INT NOT NULL,
  "evenement_id" INT NOT NULL,
  "date_ajout" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("utilisateur_id", "evenement_id") -- Un utilisateur ne peut ajouter un événement qu'une fois
);

-- Table : actualites
-- Description : Actualités de la mairie (provenant des réseaux sociaux ou créées en interne)
CREATE TABLE "actualites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL, -- Ajout du titre
  "contenu" TEXT NOT NULL,
  "type_source" VARCHAR(50) NOT NULL CHECK ("type_source" IN ('facebook', 'twitter', 'instagram', 'interne')),
  "url_source" VARCHAR(500), -- Lien vers le post original si réseaux sociaux
  "auteur_id" INT, -- NULL si provient d'un réseau social, sinon ID de l'élu/agent
  "date_publication" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ville_id" INT NOT NULL
);

-- Table : reseaux_sociaux
-- Description : Liens vers les réseaux sociaux de la mairie
CREATE TABLE "reseaux_sociaux" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ville_id" INT NOT NULL,
  "plateforme" VARCHAR(50) NOT NULL CHECK ("plateforme" IN ('facebook', 'twitter', 'instagram', 'youtube', 'linkedin')),
  "url" VARCHAR(500) NOT NULL,
  UNIQUE ("ville_id", "plateforme") -- Une ville ne peut avoir qu'un seul compte par plateforme
);

-- Table : logs_actions
-- Description : Traçabilité des actions pour conformité RGPD et audit
CREATE TABLE "logs_actions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utilisateur_id" INT,
  "action" VARCHAR(255) NOT NULL,
  "details" TEXT,
  "adresse_ip" VARCHAR(45), -- Support IPv4 et IPv6
  "date_action" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. CRÉATION DES CLÉS ÉTRANGÈRES
-- ============================================================================

ALTER TABLE "quartiers"
  ADD CONSTRAINT "fk_quartiers_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "categories_citoyens"
  ADD CONSTRAINT "fk_categories_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_categorie"
  FOREIGN KEY ("categorie_id") REFERENCES "categories_citoyens" ("id") ON DELETE SET NULL;

ALTER TABLE "signalements"
  ADD CONSTRAINT "fk_signalements_citoyen"
  FOREIGN KEY ("citoyen_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "signalements"
  ADD CONSTRAINT "fk_signalements_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_categorie"
  FOREIGN KEY ("categorie_id") REFERENCES "categories_citoyens" ("id") ON DELETE SET NULL;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_createur"
  FOREIGN KEY ("cree_par") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "questions_sondage"
  ADD CONSTRAINT "fk_questions_sondage"
  FOREIGN KEY ("sondage_id") REFERENCES "sondages" ("id") ON DELETE CASCADE;

ALTER TABLE "reponses_sondage"
  ADD CONSTRAINT "fk_reponses_question"
  FOREIGN KEY ("question_id") REFERENCES "questions_sondage" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_sondage"
  FOREIGN KEY ("sondage_id") REFERENCES "sondages" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_citoyen"
  FOREIGN KEY ("citoyen_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_reponse"
  FOREIGN KEY ("reponse_id") REFERENCES "reponses_sondage" ("id") ON DELETE CASCADE;

ALTER TABLE "thematiques_evenement"
  ADD CONSTRAINT "fk_thematiques_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_thematique"
  FOREIGN KEY ("thematique_id") REFERENCES "thematiques_evenement" ("id") ON DELETE RESTRICT;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_createur"
  FOREIGN KEY ("cree_par") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements_utilisateur"
  ADD CONSTRAINT "fk_evenements_utilisateur_user"
  FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements_utilisateur"
  ADD CONSTRAINT "fk_evenements_utilisateur_event"
  FOREIGN KEY ("evenement_id") REFERENCES "evenements" ("id") ON DELETE CASCADE;

ALTER TABLE "actualites"
  ADD CONSTRAINT "fk_actualites_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "actualites"
  ADD CONSTRAINT "fk_actualites_auteur"
  FOREIGN KEY ("auteur_id") REFERENCES "utilisateurs" ("id") ON DELETE SET NULL;

ALTER TABLE "reseaux_sociaux"
  ADD CONSTRAINT "fk_reseaux_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "logs_actions"
  ADD CONSTRAINT "fk_logs_utilisateur"
  FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateurs" ("id") ON DELETE SET NULL;

-- ============================================================================
-- 3. CRÉATION DES INDEX POUR PERFORMANCES
-- ============================================================================

-- Index sur les champs de recherche fréquents
CREATE INDEX "idx_utilisateurs_email" ON "utilisateurs" ("email");
CREATE INDEX "idx_utilisateurs_role" ON "utilisateurs" ("role");
CREATE INDEX "idx_utilisateurs_ville" ON "utilisateurs" ("ville_id");

CREATE INDEX "idx_signalements_citoyen" ON "signalements" ("citoyen_id");
CREATE INDEX "idx_signalements_etat" ON "signalements" ("etat");
CREATE INDEX "idx_signalements_type" ON "signalements" ("type_signalement");
CREATE INDEX "idx_signalements_quartier" ON "signalements" ("quartier_id");
CREATE INDEX "idx_signalements_date" ON "signalements" ("date_creation");

CREATE INDEX "idx_sondages_ville" ON "sondages" ("ville_id");
CREATE INDEX "idx_sondages_dates" ON "sondages" ("date_debut", "date_fin");

CREATE INDEX "idx_evenements_ville" ON "evenements" ("ville_id");
CREATE INDEX "idx_evenements_thematique" ON "evenements" ("thematique_id");
CREATE INDEX "idx_evenements_dates" ON "evenements" ("date_debut", "date_fin");

CREATE INDEX "idx_actualites_ville" ON "actualites" ("ville_id");
CREATE INDEX "idx_actualites_date" ON "actualites" ("date_publication");

CREATE INDEX "idx_logs_utilisateur" ON "logs_actions" ("utilisateur_id");
CREATE INDEX "idx_logs_date" ON "logs_actions" ("date_action");

-- ============================================================================
-- 4. DONNÉES D'EXEMPLE (OPTIONNEL - À SUPPRIMER EN PRODUCTION)
-- ============================================================================

-- Insertion d'une ville exemple
INSERT INTO "villes" ("nom_ville", "slogan", "logo_url", "couleurs_theme")
VALUES ('Novaville', 'Ensemble pour demain', '/assets/logos/novaville.png', '{"primary": "#3498db", "secondary": "#2ecc71"}');

-- Insertion de quartiers
INSERT INTO "quartiers" ("nom", "ville_id")
VALUES
  ('Centre-Ville', 1),
  ('Zone Industrielle', 1),
  ('Quartier Résidentiel Nord', 1),
  ('Quartier Sud', 1);

-- Insertion de catégories citoyens
INSERT INTO "categories_citoyens" ("libelle", "ville_id")
VALUES
  ('Parents d''élèves', 1),
  ('Seniors', 1),
  ('Commerçants', 1),
  ('Associations', 1);

-- Insertion de thématiques événements
INSERT INTO "thematiques_evenement" ("nom", "ville_id")
VALUES
  ('Sport', 1),
  ('Culture', 1),
  ('Citoyenneté', 1),
  ('Environnement', 1);

-- Insertion d'un utilisateur admin
INSERT INTO "utilisateurs" ("nom", "prenom", "email", "mot_de_passe_hash", "role", "ville_id")
VALUES ('Admin', 'Système', 'admin@novaville.fr', '$2y$10$example_hash_here', 'elu', 1);

-- ============================================================================
-- FIN DU SCRIPT
-- ============================================================================
