-- ============================================================================
-- BASE DE DONNÉES AMÉLIORÉE ET CORRIGÉE - APPLICATION UNICITY
-- Version : 2.1 (Corrections du bug critique + améliorations essentielles)
-- Date : 2025-12-06
-- SGBD : PostgreSQL 15+
--
-- CHANGEMENTS par rapport à v2.0 :
-- - ✅ CORRECTION BUG CRITIQUE : Contrainte UNIQUE votes_sondage
-- - ✅ Ajout colonne question_id dans votes_sondage
-- - ✅ Améliorations table utilisateurs (téléphone, RGPD, compte actif)
-- - ✅ Améliorations table signalements (adresse, contraintes GPS)
-- - ✅ Nouvelle table : fichiers (gestion uploads)
-- - ✅ Nouvelle table : historique_signalements (traçabilité)
-- - ✅ Nouvelle table : notifications (alertes citoyens)
-- - ✅ Nouvelle table : commentaires_signalement (échanges)
-- - ✅ Index de performance supplémentaires
-- ============================================================================

-- ============================================================================
-- 1. CRÉATION DES TABLES PRINCIPALES
-- ============================================================================

-- Table : villes
-- Description : Gestion des villes clientes avec personnalisation (logo, slogan, couleurs)
CREATE TABLE "villes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_ville" VARCHAR(255) NOT NULL,
  "slogan" VARCHAR(500),
  "logo_url" VARCHAR(500),
  "couleurs_theme" VARCHAR(100), -- Format JSON ou CSS (ex: {"primary": "#FF5733", "secondary": "#3498db"})
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : quartiers
-- Description : Découpage géographique des villes pour filtrage des sondages et événements
CREATE TABLE "quartiers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(255) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : categories_citoyens
-- Description : Catégorisation des citoyens pour ciblage des sondages (ex: parents d'élèves, seniors, commerçants)
CREATE TABLE "categories_citoyens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" VARCHAR(255) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : utilisateurs (AMÉLIORÉE)
-- Description : Gestion des comptes utilisateurs (citoyens, élus, agents municipaux)
CREATE TABLE "utilisateurs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(100) NOT NULL,
  "prenom" VARCHAR(100) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "mot_de_passe_hash" VARCHAR(255) NOT NULL, -- Stockage hashé (bcrypt/argon2)
  "role" VARCHAR(50) NOT NULL CHECK ("role" IN ('citoyen', 'elu', 'agent_municipal')),
  "adresse" VARCHAR(500),
  "ville_id" INT NOT NULL,
  "quartier_id" INT,
  "categorie_id" INT,
  -- ✅ NOUVEAUX CHAMPS
  "telephone" VARCHAR(20),
  "date_naissance" DATE,
  "consentement_rgpd" BOOLEAN DEFAULT false NOT NULL,
  "date_consentement_rgpd" TIMESTAMP,
  "derniere_connexion" TIMESTAMP,
  "compte_actif" BOOLEAN DEFAULT true,
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : fichiers (NOUVELLE)
-- Description : Gestion centralisée des fichiers uploadés (photos signalements, etc.)
CREATE TABLE "fichiers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_original" VARCHAR(255) NOT NULL,
  "nom_stockage" VARCHAR(255) NOT NULL UNIQUE, -- UUID généré
  "chemin" VARCHAR(500) NOT NULL,
  "type_mime" VARCHAR(100) NOT NULL, -- image/jpeg, application/pdf, etc.
  "taille_octets" BIGINT NOT NULL,
  "hash_sha256" VARCHAR(64), -- Détection des doublons
  "uploade_par" INT NOT NULL,
  "date_upload" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "check_taille_fichier" CHECK ("taille_octets" <= 10485760) -- Max 10MB
);

-- Table : signalements (AMÉLIORÉE)
-- Description : Signalements de problèmes par les citoyens (voirie, éclairage, propreté)
CREATE TABLE "signalements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "fichier_id" INT, -- ✅ Remplace photo_url (référence vers table fichiers)
  "latitude" DECIMAL(10, 8), -- Précision GPS (ex: 48.8566)
  "longitude" DECIMAL(11, 8), -- Précision GPS (ex: 2.3522)
  "adresse" VARCHAR(500), -- ✅ NOUVEAU : Adresse textuelle (geocoding inverse)
  "type_signalement" VARCHAR(50) NOT NULL CHECK ("type_signalement" IN ('voirie', 'eclairage', 'proprete', 'autre')),
  "etat" VARCHAR(50) NOT NULL DEFAULT 'enregistre' CHECK ("etat" IN ('enregistre', 'en_cours', 'resolu')),
  "citoyen_id" INT NOT NULL,
  "quartier_id" INT, -- Permet de filtrer les signalements par quartier
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "date_modification" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- ✅ NOUVELLES CONTRAINTES
  CONSTRAINT "check_latitude" CHECK ("latitude" BETWEEN -90 AND 90),
  CONSTRAINT "check_longitude" CHECK ("longitude" BETWEEN -180 AND 180)
);

-- Table : historique_signalements (NOUVELLE)
-- Description : Traçabilité des changements d'état des signalements
CREATE TABLE "historique_signalements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signalement_id" INT NOT NULL,
  "ancien_etat" VARCHAR(50),
  "nouvel_etat" VARCHAR(50) NOT NULL,
  "commentaire" TEXT,
  "modifie_par" INT,
  "date_modification" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : commentaires_signalement (NOUVELLE)
-- Description : Échanges entre citoyens et agents municipaux sur les signalements
CREATE TABLE "commentaires_signalement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signalement_id" INT NOT NULL,
  "auteur_id" INT NOT NULL,
  "contenu" TEXT NOT NULL,
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "modifie" BOOLEAN DEFAULT false,
  "date_modification" TIMESTAMP
);

-- Table : sondages
-- Description : Sondages et consultations publiques créés par la mairie
CREATE TABLE "sondages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "date_debut" TIMESTAMP NOT NULL,
  "date_fin" TIMESTAMP NOT NULL,
  "quartier_id" INT, -- NULL = tous les quartiers
  "categorie_id" INT, -- NULL = toutes les catégories
  "ville_id" INT NOT NULL,
  "cree_par" INT NOT NULL,
  CONSTRAINT "check_dates_sondage" CHECK ("date_fin" > "date_debut")
);

-- Table : questions_sondage
-- Description : Questions d'un sondage (un sondage peut avoir plusieurs questions)
CREATE TABLE "questions_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sondage_id" INT NOT NULL,
  "question" TEXT NOT NULL,
  "ordre" INT DEFAULT 1 -- Permet d'ordonner les questions
);

-- Table : reponses_sondage
-- Description : Choix de réponses possibles pour une question de sondage
CREATE TABLE "reponses_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" INT NOT NULL,
  "choix_reponse" TEXT NOT NULL
);

-- Table : votes_sondage (CORRIGÉE - BUG CRITIQUE RÉSOLU)
-- Description : Votes des citoyens aux sondages
CREATE TABLE "votes_sondage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sondage_id" INT NOT NULL,
  "citoyen_id" INT NOT NULL,
  "question_id" INT NOT NULL, -- ✅ NOUVEAU : Référence explicite à la question
  "reponse_id" INT NOT NULL,
  "date_vote" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- ✅ CORRECTION : Un citoyen ne peut voter qu'une fois PAR QUESTION (pas par sondage)
  UNIQUE ("sondage_id", "citoyen_id", "question_id")
);

-- Table : thematiques_evenement
-- Description : Thématiques des événements (sport, culture, citoyenneté, environnement)
CREATE TABLE "thematiques_evenement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(100) NOT NULL,
  "ville_id" INT NOT NULL
);

-- Table : evenements
-- Description : Événements de la ville et des associations locales
CREATE TABLE "evenements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "date_debut" TIMESTAMP NOT NULL,
  "date_fin" TIMESTAMP NOT NULL,
  "lieu" VARCHAR(500), -- Ajout du lieu de l'événement
  "thematique_id" INT NOT NULL,
  "ville_id" INT NOT NULL,
  "cree_par" INT NOT NULL,
  CONSTRAINT "check_dates_evenement" CHECK ("date_fin" >= "date_debut")
);

-- Table : evenements_utilisateur
-- Description : Événements ajoutés au calendrier personnel des utilisateurs
CREATE TABLE "evenements_utilisateur" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utilisateur_id" INT NOT NULL,
  "evenement_id" INT NOT NULL,
  "date_ajout" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("utilisateur_id", "evenement_id") -- Un utilisateur ne peut ajouter un événement qu'une fois
);

-- Table : actualites
-- Description : Actualités de la mairie (provenant des réseaux sociaux ou créées en interne)
CREATE TABLE "actualites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(255) NOT NULL, -- Ajout du titre
  "contenu" TEXT NOT NULL,
  "type_source" VARCHAR(50) NOT NULL CHECK ("type_source" IN ('facebook', 'twitter', 'instagram', 'interne')),
  "url_source" VARCHAR(500), -- Lien vers le post original si réseaux sociaux
  "auteur_id" INT, -- NULL si provient d'un réseau social, sinon ID de l'élu/agent
  "date_publication" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ville_id" INT NOT NULL
);

-- Table : reseaux_sociaux
-- Description : Liens vers les réseaux sociaux de la mairie
CREATE TABLE "reseaux_sociaux" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ville_id" INT NOT NULL,
  "plateforme" VARCHAR(50) NOT NULL CHECK ("plateforme" IN ('facebook', 'twitter', 'instagram', 'youtube', 'linkedin')),
  "url" VARCHAR(500) NOT NULL,
  UNIQUE ("ville_id", "plateforme") -- Une ville ne peut avoir qu'un seul compte par plateforme
);

-- Table : logs_actions
-- Description : Traçabilité des actions pour conformité RGPD et audit
CREATE TABLE "logs_actions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utilisateur_id" INT,
  "action" VARCHAR(255) NOT NULL,
  "details" TEXT,
  "adresse_ip" VARCHAR(45), -- Support IPv4 et IPv6
  "date_action" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table : notifications (NOUVELLE)
-- Description : Système de notifications pour les citoyens
CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "destinataire_id" INT NOT NULL,
  "titre" VARCHAR(255) NOT NULL,
  "message" TEXT NOT NULL,
  "type" VARCHAR(50) NOT NULL CHECK ("type" IN (
    'signalement_resolu',
    'nouveau_sondage',
    'nouvel_evenement',
    'reponse_agent',
    'autre'
  )),
  "lue" BOOLEAN DEFAULT false,
  "date_creation" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "date_lecture" TIMESTAMP
);

-- ============================================================================
-- 2. CRÉATION DES CLÉS ÉTRANGÈRES
-- ============================================================================

ALTER TABLE "quartiers"
  ADD CONSTRAINT "fk_quartiers_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "categories_citoyens"
  ADD CONSTRAINT "fk_categories_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

ALTER TABLE "utilisateurs"
  ADD CONSTRAINT "fk_utilisateurs_categorie"
  FOREIGN KEY ("categorie_id") REFERENCES "categories_citoyens" ("id") ON DELETE SET NULL;

-- ✅ NOUVELLE : FK pour fichiers
ALTER TABLE "fichiers"
  ADD CONSTRAINT "fk_fichiers_uploade_par"
  FOREIGN KEY ("uploade_par") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "signalements"
  ADD CONSTRAINT "fk_signalements_citoyen"
  FOREIGN KEY ("citoyen_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "signalements"
  ADD CONSTRAINT "fk_signalements_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

-- ✅ NOUVELLE : FK pour fichier_id
ALTER TABLE "signalements"
  ADD CONSTRAINT "fk_signalements_fichier"
  FOREIGN KEY ("fichier_id") REFERENCES "fichiers" ("id") ON DELETE SET NULL;

-- ✅ NOUVELLES : FK pour historique_signalements
ALTER TABLE "historique_signalements"
  ADD CONSTRAINT "fk_historique_signalement"
  FOREIGN KEY ("signalement_id") REFERENCES "signalements" ("id") ON DELETE CASCADE;

ALTER TABLE "historique_signalements"
  ADD CONSTRAINT "fk_historique_modifie_par"
  FOREIGN KEY ("modifie_par") REFERENCES "utilisateurs" ("id") ON DELETE SET NULL;

-- ✅ NOUVELLES : FK pour commentaires_signalement
ALTER TABLE "commentaires_signalement"
  ADD CONSTRAINT "fk_commentaires_signalement"
  FOREIGN KEY ("signalement_id") REFERENCES "signalements" ("id") ON DELETE CASCADE;

ALTER TABLE "commentaires_signalement"
  ADD CONSTRAINT "fk_commentaires_auteur"
  FOREIGN KEY ("auteur_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_quartier"
  FOREIGN KEY ("quartier_id") REFERENCES "quartiers" ("id") ON DELETE SET NULL;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_categorie"
  FOREIGN KEY ("categorie_id") REFERENCES "categories_citoyens" ("id") ON DELETE SET NULL;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "sondages"
  ADD CONSTRAINT "fk_sondages_createur"
  FOREIGN KEY ("cree_par") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "questions_sondage"
  ADD CONSTRAINT "fk_questions_sondage"
  FOREIGN KEY ("sondage_id") REFERENCES "sondages" ("id") ON DELETE CASCADE;

ALTER TABLE "reponses_sondage"
  ADD CONSTRAINT "fk_reponses_question"
  FOREIGN KEY ("question_id") REFERENCES "questions_sondage" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_sondage"
  FOREIGN KEY ("sondage_id") REFERENCES "sondages" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_citoyen"
  FOREIGN KEY ("citoyen_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

-- ✅ NOUVELLE : FK pour question_id
ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_question"
  FOREIGN KEY ("question_id") REFERENCES "questions_sondage" ("id") ON DELETE CASCADE;

ALTER TABLE "votes_sondage"
  ADD CONSTRAINT "fk_votes_reponse"
  FOREIGN KEY ("reponse_id") REFERENCES "reponses_sondage" ("id") ON DELETE CASCADE;

ALTER TABLE "thematiques_evenement"
  ADD CONSTRAINT "fk_thematiques_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_thematique"
  FOREIGN KEY ("thematique_id") REFERENCES "thematiques_evenement" ("id") ON DELETE RESTRICT;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements"
  ADD CONSTRAINT "fk_evenements_createur"
  FOREIGN KEY ("cree_par") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements_utilisateur"
  ADD CONSTRAINT "fk_evenements_utilisateur_user"
  FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

ALTER TABLE "evenements_utilisateur"
  ADD CONSTRAINT "fk_evenements_utilisateur_event"
  FOREIGN KEY ("evenement_id") REFERENCES "evenements" ("id") ON DELETE CASCADE;

ALTER TABLE "actualites"
  ADD CONSTRAINT "fk_actualites_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "actualites"
  ADD CONSTRAINT "fk_actualites_auteur"
  FOREIGN KEY ("auteur_id") REFERENCES "utilisateurs" ("id") ON DELETE SET NULL;

ALTER TABLE "reseaux_sociaux"
  ADD CONSTRAINT "fk_reseaux_ville"
  FOREIGN KEY ("ville_id") REFERENCES "villes" ("id") ON DELETE CASCADE;

ALTER TABLE "logs_actions"
  ADD CONSTRAINT "fk_logs_utilisateur"
  FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateurs" ("id") ON DELETE SET NULL;

-- ✅ NOUVELLES : FK pour notifications
ALTER TABLE "notifications"
  ADD CONSTRAINT "fk_notifications_destinataire"
  FOREIGN KEY ("destinataire_id") REFERENCES "utilisateurs" ("id") ON DELETE CASCADE;

-- ============================================================================
-- 3. CRÉATION DES INDEX POUR PERFORMANCES
-- ============================================================================

-- Index sur les champs de recherche fréquents (ORIGINAUX)
CREATE INDEX "idx_utilisateurs_email" ON "utilisateurs" ("email");
CREATE INDEX "idx_utilisateurs_role" ON "utilisateurs" ("role");
CREATE INDEX "idx_utilisateurs_ville" ON "utilisateurs" ("ville_id");

CREATE INDEX "idx_signalements_citoyen" ON "signalements" ("citoyen_id");
CREATE INDEX "idx_signalements_etat" ON "signalements" ("etat");
CREATE INDEX "idx_signalements_type" ON "signalements" ("type_signalement");
CREATE INDEX "idx_signalements_quartier" ON "signalements" ("quartier_id");
CREATE INDEX "idx_signalements_date" ON "signalements" ("date_creation");

CREATE INDEX "idx_sondages_ville" ON "sondages" ("ville_id");
CREATE INDEX "idx_sondages_dates" ON "sondages" ("date_debut", "date_fin");

CREATE INDEX "idx_evenements_ville" ON "evenements" ("ville_id");
CREATE INDEX "idx_evenements_thematique" ON "evenements" ("thematique_id");
CREATE INDEX "idx_evenements_dates" ON "evenements" ("date_debut", "date_fin");

CREATE INDEX "idx_actualites_ville" ON "actualites" ("ville_id");
CREATE INDEX "idx_actualites_date" ON "actualites" ("date_publication");

CREATE INDEX "idx_logs_utilisateur" ON "logs_actions" ("utilisateur_id");
CREATE INDEX "idx_logs_date" ON "logs_actions" ("date_action");

-- ✅ NOUVEAUX INDEX pour améliorations
CREATE INDEX "idx_utilisateurs_telephone" ON "utilisateurs" ("telephone");
CREATE INDEX "idx_utilisateurs_actif" ON "utilisateurs" ("compte_actif");

CREATE INDEX "idx_fichiers_hash" ON "fichiers" ("hash_sha256");
CREATE INDEX "idx_fichiers_uploade_par" ON "fichiers" ("uploade_par");

CREATE INDEX "idx_signalements_quartier_etat" ON "signalements" ("quartier_id", "etat");
CREATE INDEX "idx_signalements_geo" ON "signalements" ("latitude", "longitude");

CREATE INDEX "idx_historique_signalement" ON "historique_signalements" ("signalement_id");
CREATE INDEX "idx_historique_date" ON "historique_signalements" ("date_modification");

CREATE INDEX "idx_commentaires_signalement" ON "commentaires_signalement" ("signalement_id");
CREATE INDEX "idx_commentaires_auteur" ON "commentaires_signalement" ("auteur_id");

CREATE INDEX "idx_votes_question" ON "votes_sondage" ("question_id");

CREATE INDEX "idx_notifications_destinataire" ON "notifications" ("destinataire_id");
CREATE INDEX "idx_notifications_non_lues" ON "notifications" ("destinataire_id", "lue") WHERE "lue" = false;

-- ============================================================================
-- 4. DONNÉES D'EXEMPLE (OPTIONNEL - À SUPPRIMER EN PRODUCTION)
-- ============================================================================

-- Insertion d'une ville exemple
INSERT INTO "villes" ("nom_ville", "slogan", "logo_url", "couleurs_theme")
VALUES ('Novaville', 'Ensemble pour demain', '/assets/logos/novaville.png', '{"primary": "#3498db", "secondary": "#2ecc71"}');

-- Insertion de quartiers
INSERT INTO "quartiers" ("nom", "ville_id")
VALUES
  ('Centre-Ville', 1),
  ('Zone Industrielle', 1),
  ('Quartier Résidentiel Nord', 1),
  ('Quartier Sud', 1);

-- Insertion de catégories citoyens
INSERT INTO "categories_citoyens" ("libelle", "ville_id")
VALUES
  ('Parents d''élèves', 1),
  ('Seniors', 1),
  ('Commerçants', 1),
  ('Associations', 1);

-- Insertion de thématiques événements
INSERT INTO "thematiques_evenement" ("nom", "ville_id")
VALUES
  ('Sport', 1),
  ('Culture', 1),
  ('Citoyenneté', 1),
  ('Environnement', 1);

-- Insertion d'utilisateurs de test
INSERT INTO "utilisateurs" ("nom", "prenom", "email", "mot_de_passe_hash", "role", "ville_id", "quartier_id", "telephone", "consentement_rgpd", "date_consentement_rgpd")
VALUES
  ('Admin', 'Système', 'admin@novaville.fr', '$2y$10$example_hash_here', 'elu', 1, 1, '01.23.45.67.89', true, CURRENT_TIMESTAMP),
  ('Dupont', 'Marie', 'marie.dupont@email.fr', '$2y$10$example_hash_here', 'citoyen', 1, 1, '06.12.34.56.78', true, CURRENT_TIMESTAMP),
  ('Martin', 'Jean', 'jean.martin@email.fr', '$2y$10$example_hash_here', 'agent_municipal', 1, NULL, '01.23.45.67.90', true, CURRENT_TIMESTAMP);

-- ============================================================================
-- 5. COMMENTAIRES ET VUES UTILES (OPTIONNEL)
-- ============================================================================

-- Vue : Statistiques des signalements par quartier
CREATE OR REPLACE VIEW "vue_stats_signalements_quartier" AS
SELECT
  q.id AS quartier_id,
  q.nom AS quartier_nom,
  v.nom_ville,
  COUNT(s.id) AS nb_total_signalements,
  COUNT(s.id) FILTER (WHERE s.etat = 'resolu') AS nb_resolus,
  COUNT(s.id) FILTER (WHERE s.etat = 'en_cours') AS nb_en_cours,
  COUNT(s.id) FILTER (WHERE s.etat = 'enregistre') AS nb_en_attente,
  ROUND(
    100.0 * COUNT(s.id) FILTER (WHERE s.etat = 'resolu') / NULLIF(COUNT(s.id), 0),
    2
  ) AS taux_resolution_pct
FROM quartiers q
JOIN villes v ON q.ville_id = v.id
LEFT JOIN signalements s ON s.quartier_id = q.id
GROUP BY q.id, q.nom, v.nom_ville;

-- Vue : Sondages actifs
CREATE OR REPLACE VIEW "vue_sondages_actifs" AS
SELECT
  s.*,
  v.nom_ville,
  u.nom || ' ' || u.prenom AS createur_nom,
  COUNT(DISTINCT vs.citoyen_id) AS nb_participants
FROM sondages s
JOIN villes v ON s.ville_id = v.id
JOIN utilisateurs u ON s.cree_par = u.id
LEFT JOIN votes_sondage vs ON vs.sondage_id = s.id
WHERE s.date_fin >= CURRENT_TIMESTAMP
GROUP BY s.id, v.nom_ville, u.nom, u.prenom;

-- ============================================================================
-- FIN DU SCRIPT
-- ============================================================================

-- NOTES IMPORTANTES :
-- 1. Ce script crée une base de données propre et fonctionnelle
-- 2. Le bug critique des votes_sondage a été corrigé
-- 3. Les améliorations essentielles ont été intégrées
-- 4. Pour aller plus loin, consultez le fichier ANALYSE_BD_AMELIORATIONS.md
-- 5. Pensez à changer les mots de passe par défaut en production !
